### PR TITLE
make MsgPackContext thread-safe 

### PR DESCRIPTION
**Pull request by pavlua**
fix for https://github.com/progaudi/MsgPack.Light/issues/77

### CODE REVIEW

**Review by aensidhe — APPROVED** [review]
So, it was a deliberate decision not to use ConcurrentDictionary here to reduce memory footprint. But yeah, ok, looks legit for now.  CI looks broken, will need to look into it. 

I'll be able to do it in late August for sure. Can't promise anything before that.

**Comment by pavlua** [comment]
@aensidhe hi,
Taking into account your busyness, I have prepared a PR https://github.com/progaudi/MsgPack.Light/pull/90 for updating the CI process on Github Actions. Can you take a look on it pls?

**Comment by aensidhe** [comment]
@pavlua please update this PR and let's merge it.

**Comment by pavlua** [comment]
@aensidhe It turns out there is a problem with CI: secrets are not passed to the runner when a workflow is triggered from a forked repository (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories). This means that dotnet nuget push step fails, since it uses nuget API key. Possible workaround is to use 'pull_request_target' event instead of 'pull_request' in ci.yml, I'll try to investigate

**Comment by pavlua** [comment]
@aensidhe hi! As I wrote you in the previous message, there are some issues with CI in the case when PR comes from forked repo (basically, my case). I made some fixes in CI in new PR https://github.com/progaudi/MsgPack.Light/pull/93. Please, take a look.

**Pull request merged**
